version: "3"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
virtualmachines:
- name: workstation
  image: ubuntu-os-cloud/ubuntu-2004-lts
  shell: /bin/bash
  machine_type: n1-highcpu-8
  allow_external_ingress:
  - http
  - https
  - high-ports
gcp_projects:
- name: gcpproject
  services:
  - cloudresourcemanager.googleapis.com
  - compute.googleapis.com
  - container.googleapis.com
